### ISSUE TITLE
리뷰 작성시 화면 내려감

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#124]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/1cbc0fdc-6d62-44cb-a99a-943c1438a5f6

**Comment by Minoyam** [comment]
670ec411fbd91daf506bbdac4ca4a9f7de98db7c

**Comment by seungh0** [comment]
여전히 존재하네요.. 기종은 갤럭시 s9입니다

**Comment by seungh0** [comment]
고생하셨습니다~ 확인했습니다!!
