### ISSUE TITLE
리뷰 목록에서 탭 변경하면 리뷰 맨 위로 보여줘야 할거 같아요

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#126]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/33b44217-aa07-4790-964f-e2a93105c569

**Comment by Minoyam** [comment]
0374fb3f0cee270d6865af24e0c4404b426a8fcf
