### ISSUE TITLE
즐겨찾기 추가/삭제시 기존 카운트와 상관없이 1,0으로 고정됨

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#127]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/37114398-b739-49d5-a072-b799e3d82823

- 추가로, 일반 가게의 경우 내가 누른 즐겨찾기가 유지되지 않습니다 (상세화면 뒤로 갔다 돌아오면)

**Comment by Minoyam** [comment]
a9e533dba8a3d36d040e45aeb66cb72698187ff0
추가로 남겨주신것도 해결했습니다.
