### ISSUE TITLE
가게 수정시 가게 형태 변경 안되는 곳이 있고, 문구가 다름

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#128]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/14dff89b-3313-4566-a65a-7cb385b197cd

- 편의점인경우 안됨
- 노점 /길거리 문구 다름
- 등록쪽도 동일함

**Comment by Minoyam** [comment]
b593172accde6ffbb8aee70b0187529b59f8a434
