### ISSUE TITLE
메뉴 수정시 그루핑이 안되는 거 같음 + 버그

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#129]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/214f1163-c880-4360-be0f-429927055d28

**Comment by Minoyam** [comment]
b6821f25c9d33aa5cd68820aadbe765df3ec09ac
