### ISSUE TITLE
사장님 가게는 아직 방문 인증이 없어서 필터링이 사라져야할 거 같습니다

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#130]
![Screenshot_20231103-210100_()3](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/a5094491-1760-451b-aff5-12e4fc09bf6c)

**Comment by Minoyam** [comment]
e680ede53eedb05764eab53e583f6cc52cdd1462

**Comment by seungh0** [comment]
확인 완료했습니다! 고생하셨습니다
