### ISSUE TITLE
가게 조회시 삭제된 가게면 뒤로 보내야할거 같습니다

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#131]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/b9bd5e89-cdf0-4877-b12d-7212dd8fe1c8

**Comment by Minoyam** [comment]
주변 가게 API 호출시 삭제된 가게도 보여주는건가요?
아니면 해당 영상에서 보여지는 삭제된 가게는 신고를 했을 때 3번이 누적된 가게라 삭제된 뒤 홈 화면에는 남아있는 가게인건가요??

제가 플로우를 제대로 숙지를 못하고 있어서 어떻게 동작하는게 맞는건지 설명 한번만 부탁드리겠습니다 ㅠㅠ

**Comment by seungh0** [comment]
주변 가게 조회 당시에는 삭제된 가게는 조회되지 않는데요. 그 사이에 내가 삭제하거나 다른 사람이 삭제하는 케이스가 발생할 수 있습니다

**Comment by Minoyam** [comment]
feae7a6d669a94b7fd4a909f2db6eafdf0556c60
