### ISSUE TITLE
거리순 보기, 최신순 보기가 반대로 된거 같아요 (뭐가 맞는거죠.)

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#133]
![Screenshot_20231103-211840_()3](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/49c833af-f338-4a88-b7f0-f5aba51aeb79)

ios랑 반대로 동작하네요 (@Hyunsik-Yoo )
ios > 최신순이 위에 보이면 최신순으로 노출
android > 최신순이 위에 보이면 반대의 거리순이 노출

- 정렬 기준이 2개 넘어갈 수 있으니 반대가 되어야 하지 않을까 싶네요

**Comment by Minoyam** [comment]
5b8a0402af5e2180410b1a1ddf7f864a49325263
