### ISSUE TITLE
가게 이미지 등록 후 상세 화면으로 복귀시 카운트가 증가하지 않음

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#134]

**Comment by Minoyam** [comment]
989178f8e5b27f633a17eaf33e751f04ec123c2f

**Comment by seungh0** [comment]
4.0.0-test03으로 확인중인데, 해당 버전 기준으로 수정된 걸까요? (계속 존재해서 공유드립니다)

**Comment by seungh0** [comment]
추가로 이미지 목록에서 이미지 등록하면 반영이 앱 내에 안되어 있네여

**Comment by seungh0** [comment]
@Minoyam 
확인 했습니다. 근데, 이미지 목록에서.. 이미지를 등록하면 반영이 안되는 버그가 추가로 있었네요..

**Comment by Minoyam** [comment]
582042751a09b3a1ea684d93de5481cad5d3c61b

**Comment by seungh0** [comment]
카운트는 확인했는데, 이미지 목록에서 이미지를 등록하면, 앱내에서 리스트에 추가하는 작업은 안되어 있는거 같습니다

**Comment by Minoyam** [comment]
리스트 추가되는 것도  확인했는데 아직까지 동일하게 발견될까요??
이미지 목록이라는게 가게 상세페이지가 아닌 가게 이미지 리스트 페이지 말씀하시는건가요??

**Comment by seungh0** [comment]
앗 넵 맞습니다

**Comment by Minoyam** [comment]
아 가게 상세페이지만 확인해서.. 가게 이미지 리스트 페이지도 확인해보겠습니다..ㅋㅋ

**Comment by Minoyam** [comment]
a3b618f4e2f5ab2c80244d3f344758df2cab4342
