### ISSUE TITLE
사장님 가게로 푸시 랜딩시 일반 가게로 감

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#135]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/e31d1d49-0831-4ca3-8407-9acf37865c0f

푸시 테스트 필요시 테스트 api 공유 드릴게여

**Comment by Minoyam** [comment]
해당 영상 사장님 가게로 푸시 랜딩시 사장님 가게로 간거 아닌가용?

**Comment by seungh0** [comment]
아 맞네요 옛날 UI랑 헷갈렸습니다
