### ISSUE TITLE
가게 카드 광고 문구 미노출

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#137]
![Screenshot_20231104-002106_()3](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/0a2b3b71-fa3c-4192-9fd7-6f0a580513c7)

**Comment by seungh0** [comment]
참고 자료입니다 (ios)

![IMG_2414](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/6ba73c6c-6f0f-4e31-9c33-8a0e2835d210)

**Comment by Minoyam** [comment]
7202cb474a794381563173c2a572f078edbd30aa

**Comment by seungh0** [comment]
확인 완료했습니다! 고생하셨습니다
