### ISSUE TITLE
사장님 가게 상세 화면 오픈 해도 "준비중"이라고 노출

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#138]
![Screenshot_20231104-002854_()3](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/9b48baaa-965e-4611-981b-a19eb779061f)

**Comment by Minoyam** [comment]
e831df8839cb3726fabc73154b5fe26eca032db5
