### ISSUE TITLE
가게 이미지 목록 해상도

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#139]
![Screenshot_20231104-003514_()3](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/e104660f-95ad-4552-91cd-99521272dd3a)

해상도가 좀...
제 공기계가 문제일수도

**Comment by Minoyam** [comment]
d614f3af03e23cf3ee7b132b9ddc0876743b8e18

피그마상에서 160 * 160 사이즈로 사진이 고정인거 같아서 일부로 늘려서 표시하긴한건데 일단 비율에 맞게 나오도록 수정해놨습니다.

**Comment by seungh0** [comment]
확인 완료했습니다! 고생하셨습니다
