### ISSUE TITLE
회원가입 중 뒤로 돌아가면 구글 로그인 클릭 안됨

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#142]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/e97bb763-b773-4ccf-b01b-4e2e2628108c

**Comment by Minoyam** [comment]
8e454f181987f75f8f78f5309fa8af72ff940cd3

**Comment by seungh0** [comment]
확인 완료했습니다! 고생하셨습니다
