### ISSUE TITLE
회원가입시 회원가입 api 호출하고 성공시 마수신 받아야할 것 같음

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#143]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/4fe40629-eed8-4ec6-af33-2bdf75d525b8

**Comment by seungh0** [comment]
#144 와 관련된 이슈로 보입니다

**Comment by Minoyam** [comment]
3292ce7a2a67d3d08bcfe36c7d7df495c5514ce8

**Comment by seungh0** [comment]
확인했습니다! 고생하셨습니다~
