### ISSUE TITLE
회원가입시 마수신 동의 2번 뜸

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#144]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/cbf0e594-a51f-432c-b6c5-119a6f59f6cb

**Comment by Minoyam** [comment]
3292ce7a2a67d3d08bcfe36c7d7df495c5514ce8

**Comment by seungh0** [comment]
확인 완료했습니다! 고생하셨습니다
