### ISSUE TITLE
[가게 뷰] 리스트 뷰 <-> 지도 뷰 간에 옵션이 반대로 되어 있음 (거리순, 최신순)

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#146]
- 지도뷰, 리스트뷰에서 선택된 거리순/최신순이 반대로 된 것 같습니다

**Comment by Minoyam** [comment]
adc89e4cc42918900d6b550b23b82ef11472a62c

현식님한테 여줘봐서 거리순이 보여지고 있으면 거리순으로 / 최신순이 보여지고 있으면 최신순으로 정렬되게 수정했습니다!
지도뷰는 수정을 했었는데 리스트뷰를 수정을 안해서 반대로된거처럼 보였던거 같습니다
