### ISSUE TITLE
가게 상세 - 이미지 해상도

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#147]
![IMG_2507](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/assets/48153675/2908de71-3f36-41a4-84f9-3341296e2b3d)

가게 상세 화면에서 이미지 해상도가 깨지는거 같아요

**Comment by Minoyam** [comment]
6b6f4250bd3871b85be92534adce7cf5c46d48eb
