### ISSUE TITLE
[커뮤니티 투표] 투표 상세페이지로 이동하는 딥 링크 생성 부탁드리겠습니다!

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#154]
푸시 클릭시 투표 상세 페이지로 이동할 수 있는 앱 스킴이 필요한 상황입니다

투표 상세 페이지로 이동하는 딥링크 생성 필요
- 앱 스킴: /pollDetail?pollId={{POLL_ID}}

**Comment by JeongJinyong** [comment]
@seungh0 혹시 push 투표로 날릴만한 api있을까요??
