### ISSUE TITLE
[커뮤니티 투표] 자신이 작성한 댓글에는 "신고"가 아닌 "삭제" 이 노출되어야할거 같음

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#159]
자신이 추가한 댓글에는 "신고"가 아닌 "삭제"가 노출되어야할 거 같습니다

- 어쩔때는 동작하는거 같은데.. 응답의 isOwner로 구분하는 걸까요..?

**Comment by JeongJinyong** [comment]
아하 잘못사용하고있었네요 작성자는 isWriter를 사용하도록 수정하고 자신댓ㅁ글은 isOwner로 사용하도록 수정하겠습니다 반대로 사용중이였네요 ㅋㅋㅋㅋㅋ
