### ISSUE TITLE
[마이페이지] 삭제된 가게 접근시 빈 화면이 노출됩니다

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#68]
![B62DE0DE-AB89-4CFB-8A0A-7F11FCA3A127](https://user-images.githubusercontent.com/48153675/206888212-9c4b59af-f3b9-424b-ad76-577802822632.jpeg)

- 즐겨찾기마이페이지에서 (삭제된 가게) 클릭시, 삭제된 가게 접근시 다음과 같이 빈 화면이 보입니다

**Comment by Minoyam** [comment]
삭제한 가게는 필터링 처리하여 안 보이게 수정했습니다.
