### ISSUE TITLE
[가게 상세화면] 즐겨찾기를 한 후에 가게 상세화면을 들어가서 즐겨찾기 버튼을 누르면 다시 한번 추가됩니다.

### ISSUE THREAD

**Issue by Hyunsik-Yoo** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#69]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

https://user-images.githubusercontent.com/7058293/206944094-81bc7d7f-f969-4b86-95ca-334058053952.mp4

- 즐겨찾기가 이미 되어있는 가게의 상세화면에 진입하면 즐겨찾기 마커가 정상적으로 ON되어있습니다.
- 즐겨찾기 버튼을 터치하면 OFF가 되어야할 것 같은데 다시 즐겨찾기 추가되었다는 토스트 메시지와 함께 ON상태가 유지됩니다.

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v3.0.4
- 디바이스: Galaxy S8+

## 예상되는 원인이 있으면 적어주세요.
- 즐겨찾기 ON,OFF 순서가 고정되어 있는게 아닌가..?? 예상해봅니다.

**Comment by seungh0** [comment]
이거 수정된거 확인했습니다~
