### ISSUE TITLE
[즐겨찾기 뷰어 화면] 메뉴가 노출되어야 하는 곳에 가게 이름이 노출되는 듯 합니다.

### ISSUE THREAD

**Issue by Hyunsik-Yoo** [3dollar-in-my-pocket/3dollar-in-my-pocket-android#85]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

<img src="https://user-images.githubusercontent.com/7058293/219830061-583daade-f111-43b8-b1d1-32143a6e9386.jpg"  width="300">

- 메뉴가 노출되어야 하는 곳에 가게 이름이 노출되는 듯 합니다.

## 재현 방법
- 즐겨찾기 링크 실행

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v3.1.5(50)
- 디바이스: Galaxy S8 +
- Android 버전: 9

## 예상되는 원인이 있으면 적어주세요.
- 가게 이름이 두번 찍히는 것 같습니다.

**Comment by JeongJinyong** [comment]
남겨주신 해당 이슈 메뉴가아니라 카테고리명인거죠??

**Comment by Hyunsik-Yoo** [comment]
아아 네네!! 카테고리명 맞습니다! @JeongJinyong
